### ISSUE TITLE
Different errors

### ISSUE THREAD

**Issue by dislexicboy** [derekhe/waveshare-7inch-touchscreen-driver#11]
Hi, I tried using your driver to get my touchscreen to work. I just got a Raspberry Pi 2, with the waveshare 7inch touchscreen, but I cannot get the driver to work. First I tried using it on Jessie, all I got was the act light on the raspberry pi would stay off, and the screen was just white. Then I downloaded wheezy, and tried to install, and the act light will stay off, but on the screen all I see is a bliking white line. On both setups, the act light would turn on, flash a few times, then turn off.

**Comment by JendrikDerWeise** [comment]
Is it the 800x480 one?
Sounds like you have to configure the boot/config.txt
