### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jamesadds** [derekhe/waveshare-7inch-touchscreen-driver#13]
I have the newer version of this screen the C model, i think the only difference is that this one runs at 1024x600 res instead. Can someone please tell me if this driver will work with my Pi2+Screen and what i need to edit, Thanks. http://www.waveshare.com/wiki/7inch_HDMI_LCD_(C)

**Comment by Stahl80** [comment]
I would think that you at least have to edit the resolution output. I believe that can be fixed quite easy in a configfile in the pi, google it and you will find which one. About the touch I have no ide. Guess you could try with a second SD card so you don't corrupt your current install.

**Comment by goutamenara** [comment]
Hi jamesadds I just edited in config.txt 
hdmi_cvt 1024 600 60 6 0 0 0
and it is working fine

**Comment by andriuwe4ka** [comment]
@goutamenara yes, view works pretty fine after this correction, but touch seems a bit crazy (jumps, multiclicks, frame selection....).
i reviewed touch scripts in repo and didn't found how to fix touch =(
any ideas?

**Comment by JendrikDerWeise** [comment]
I´ve got the same problem.
No solution still yet...
