### ISSUE TITLE
How to rotate touchscreen?

### ISSUE THREAD

**Issue by goutamenara** [derekhe/waveshare-7inch-touchscreen-driver#14]
Hi i am using your driver for Waveshare 7inch HDMI Screen. I would like to use the screen in a 180 degree rotated orientation. I had rotated the display using display_rotate=2 in config.txt. How to rotate the touch interface by 180 degree ?

**Comment by carlosinters** [comment]
This is my first post but im glad to help anyone who uses this driver and want to rotate the touchscreen, lcd_rotate does not work. So The first step is to use display_rotate=2 and after that open a terminal and use 

`cd  /usr/bin`

then use `sudo leafpad touch.py`

and go down until you find 

if btnLeft:
            input_device.emit(uinput.ABS_X,x , True)
            input_device.emit(uinput.ABS_Y,y, True)

Replace the x with `1024-x` and the y with `600-y`

This is simply rotating the coordinates by 180 degrees. Hope i can help someone :)
