### ISSUE TITLE
Pro version features

### ISSUE THREAD

**Issue by derekhe** [derekhe/waveshare-7inch-touchscreen-driver#15]
Hi there, 

If I could provide a pro version, what kind of features do you like? Please give me your idea. Thank you.

**Comment by derekhe** [comment]
![mm_facetoface_collect_qrcode_1453548194990](https://cloud.githubusercontent.com/assets/1734077/12529943/8d9d7234-c207-11e5-8b97-f2611e7d6e86.png)
![Uploading 1453548178027.jpg…]()

**Comment by derekhe** [comment]
![mm_facetoface_collect_qrcode_1453548194990](https://cloud.githubusercontent.com/assets/1734077/12529973/44b49d62-c208-11e5-9ef1-5439685eee43.png)
![1453548178027](https://cloud.githubusercontent.com/assets/1734077/12529974/45111a6a-c208-11e5-9055-645da71b6e48.jpg)

**Comment by luka1995** [comment]
Hi @derekhe,

- calibration
- multitouch
- zoom
- maybe some settings file to edit all options or something like that ;)

Luka

**Comment by derekhe** [comment]
What do you mean by "zoom"?

**Comment by luka1995** [comment]
Zoom like iphone images if it possible? but this is not that important
