### ISSUE TITLE
Pro feature

### ISSUE THREAD

**Issue by JendrikDerWeise** [derekhe/waveshare-7inch-touchscreen-driver#16]
The calibration-thing would be nice.
Did you received my emails?
The driver isn´t working correctly with my display. Have a look at this video:
https://drive.google.com/file/d/0B0m0Q0_2wdgkWXpHRUNVaVlWdDQ/view?usp=sharing

**Comment by derekhe** [comment]
I watched the video but I think it is not a calibrate issue. Is that a 7-inch or 5-inch display? What is your actual type of the screen?

**Comment by JendrikDerWeise** [comment]
Hi,
it is 7" and the C version.
1024x600 resolution.
I've send it back, because manufacture couldn't help me. Stupid company ^^
Am 28.01.2016 3:52 vorm. schrieb "hesicong" <notifications@github.com>:

**Comment by derekhe** [comment]
ok. sorry for this. I don't have a 1024x600 so I can't test it.
