### ISSUE TITLE
5inch HDMI LCD

### ISSUE THREAD

**Issue by loentar** [derekhe/waveshare-7inch-touchscreen-driver#3]
Not a real issue.

I successfully get it working with this display: http://www.waveshare.com/wiki/5inch_HDMI_LCD_(B)

With this driver device gets recognized, but the cursor is just jumping around. 

The difference in protocol is a packet length: it's 22 bytes instead of 25.

If you have this display and want to get touch working, replace this line in /usr/bin/touch.py:

```
b = f.read(25)
```

to this:

```
b = f.read(22)
```

and restart the touch service:

```
sudo service touch restart
```

After that cursor stops jumping and you can try to calibrate touchscreen.

**Comment by derekhe** [comment]
Hi, 
Thanks for using this driver. argon40 created a patch for 5-inch, you can have a look:
https://github.com/argon40/wavesahre-7inch-touchscreen-driver

When I have time I can merge them together.
