### ISSUE TITLE
7" eleduino touchscreen

### ISSUE THREAD

**Issue by b3joel** [derekhe/waveshare-7inch-touchscreen-driver#4]
When I use the image that comes with this touchscreen, touch works everywhere (kivy, X, python apps, everything). Problem for me is, the GPIO pins don't work.

Using a fresh wheezy or KivyPie and your drivers makes everything work! Just no touch in Kivy apps. Touch in X and python games/apps work. Just not Kivy :-( Any ideas what I could try?

I did try the fix that adds a few lines to the config.ini of Kivy... but no success.

**Comment by derekhe** [comment]
I don't know Kivy. The way my driver is working is that it simulate the mouse event (not touch event). I guess if any program doesn't read from the mouse event, it fails. Could you try find out what event is Kivy listening to?

**Comment by b3joel** [comment]
Hi,

Looking at the documentation: i've found this: http://kivy.org/docs/api-kivy.input.html?highlight=input#kivy.input

When you asked where Kivy listens to, I thought I'll just enable the mouse and I'm done.
Mouse now works in every kivy app, but the touchs doesn't. This is so weird. When I run the app windowed (in raspbian), touch works outside the app.

In the kivy config.ini, [input] is set to:
[input]
mouse = mouse
mtdev_%(name)s = probesysfs,provider=mtdev
hid_%(name)s = probesysfs,provider=hidinput

**Comment by derekhe** [comment]
I guess you should modify my source code to send touch event to Kivy instead of mouse event.

**Comment by b3joel** [comment]
I'd have no idea where to start. Any hints to where I should look?

**Comment by lozuwa** [comment]
hello, have you gotten to any solution. I am facing the same issue.

**Comment by derekhe** [comment]
I have no solutions because I've upgraded my touch screen so that screen driver is not needed.
